### ISSUE TITLE
Fix sitetest1 & sitetest2

### ISSUE THREAD

**Issue by glass51** [MaximumADHD/Roblox-Client-Tracker#24]
Currently roblox made it so the deployhistory for channels are hidden like this:
![image](https://user-images.githubusercontent.com/78827595/190836826-9c9286dc-97e4-41a8-a5d6-626c046926d8.png)
 Making Roblox Client Tracker Useless for the sitetests.

The only current way to get the version hashes now is to call on https://setup.rbxcdn.com/channel/{channelName}/versionQTStudio every 10-30 minutes to see if they added a new deploy or not.

**Comment by regginator** [comment]
Yeah, new entries on sitetest are giving `version-hidden` for ver ID. I'd think this will be the same in the next production version next week.

I think it's **just** DeployHistory, though. You're still able to use ALL previous setup endpoints like normal. (Ex WindowsClient http://setup.sitetest2.robloxlabs.com/version.txt)

Best way would probably be w/ setup.rbxcdn.com/channel endpoints. I don't believe setup.roblox/robloxlabs has any ratelimits by AWS whatsoever.

**Comment by azumanga** [comment]
I agree, this is a huge issue for mod manager. It appears that version guids are not shown on sitetest, however version guids are shown on channel branches.
https://setup.rbxcdn.com/channel/zcanary/DeployHistory.txt
https://setup.rbxcdn.com/channel/zintegration/DeployHistory.txt
https://setup.rbxcdn.com/channel/zqtitanstudiorelease/DeployHistory.txt

zIntegration is the only one with hidden logs so far. The easiest way to access is to check for a new `Studio64` release and then if the release is hidden, look on https://setup.rbxcdn.com/channel/zintegration/versionQTStudio for the newest version. Seems kinda hacky, but it works. Hopefully Roblox doesn't further break DeployHistory tools by hiding logs on `zCanary` and `zQtitanStudioRelease`.
